language: java
jdk:
  - openjdk8

sudo: required

services:
  - docker

cache:
  directories:
    - "$HOME/.m2"

env:
  global:
    - SERVICE_NAME="solr"
    - LATEST_TAG="latest"
    # this needs to be updated on every release
    - SOLR_CURR_VERSION="6.6.9"
    - secure: QAMZoUqDlXmnDYeAC510h+3pE+3vOrOpjImWGW2JBCkt3J8Mx9yH6iece+u9/EmyKyPOtwTsPi8S5qlSoPaQdzoxAp9S3RXURMCSInlSv4a85nt1dApAPlN6RtgALDcQx9Z84WiCB/FbYbf3LEhilvJrSe+cZwThgYN/+f2i9j1j/Uc5wBGI6SY9ardQsPhiMuMmArSW+t/rKmHHWc3ZtcbVXNQqwhKN0Sxk04I857n8Tfwv8uGZTQi54shE/yBUlu3WL4Hqxk2uDP9bko4QB3yiFX9rRwoEkjKBiYZE+TnE3ishPDrdaFxGKF8CbcMKCSblCcdz58dqBCm1cDeRKZoF5uKYw2ygWpAMfoqW3SoG3vIa18OdJd0ZzkpmPyDdzzyIcKkffAGSgZPOZDkmRAyD4/2PGUCOUXOIzyH2HqzFyOWyXMiHDI34BZMZc+wtUFwAK6+OhJEOWLL6iqXrtze4nYVZ9ozKTkVzDCRSwlkUCXwntTfdE0S/OBKFO6poFKOW/YBKNkHhVKAlcUnzk9WjnM9RHp09i4De3NrCUcOa/72y7e2zZXUz9tcVGOClNUpBT81o/LceY9/aNeDGR113N5GoK8I1POGsacCYA4b3FysnzKQx3dp/LlY5pFUTX8TklG3JW0v2dPn/Pb+fBvl/antMMA3CVDjDlDKAeis=
    - secure: XKag1GJ/ZncVCv0zg/WjXa+qxfKlPFestfWdXJUtR0R7P46G3sY8cM8mWNyGzdji1MTW3U44tzWf6Gz1MP50+1dc9mTAO38CqpeGvyV7ZloKhppwgy4nz3XHp2g9TVDFp15MdFDnOc8ysKr3ODU4ksCA/j0bXqWDdxAKsH+VyDOieoKwoiiYP0ol1PodVBWNYqdsx7UZ2OIIkzAE30AfGoZs3Jq3v3TaoLOLucfg7K8v2iYDea2ef5iog75Lz92AQJw1PM2LR4cRFpEKdnqmGMpwoUAWnipPjivyWcTm5TGT5RYe0mDfLMQwsI7/X8j/Ko/LZ30bReJ8SWI6+IY0bEQQnI6BYFPizk58fEyuIsAcg+Sk3T1Vbr3lU9AnXtgdMlMvK+FC/mxQgIT6Bramd2I8ypkjzk2iaTjbRCFaRT9jpfXxFUIaYcYwzrJuIfnVCxHkB6lIYVQik2oGX8Nfcc+khWqF75fyctGEmOCenVwEX48Y/UjFDEskfdHiKW+e4El6BFfI8J4h2ZqwXg4y1GQP/fb0Vt6gQ4UJWPk8Zg/W5nctRzLoEbXwWEY9GPWorpqMhosp3w/LhrQL3s0SNl/gnlHjNzaFkG1IOvBelsoshXFESRjLGeZXQuGGTnVKtvLQLxjWrL8U+v9LhB9Sv6ZPjixCmCIN1ks93f4zT90=
    - secure: WxU8Sn2gAjqIDyUubrXXx2rJFTAwcfFLz8LTnBMNVXu1JKPQ95i6/Z1pJCu/xyJmpxCqcEJwAtu1jjzh03z0FZAW6VGwzd1o4v3esNF+wHIFpFh92wRGtRxkE86uZWInJhGeVfd9/bCN16qzD76uTJWbmKXkJ8CZ3PDZEralGpbXyE3zb7KGpEecFdpYrHGLdoFboKnTRZiETtyPzhStATqp+atNgpemtKVtSmeArXQLR10o0AupaK5WnCL69p+zi8GzcpN5fwfU6meXcKRmbumY/rrHVASaKil0Aa8CO/ed8KF5X/IA2XirmO1BKm1+lkyxWctgx4CTL2aegyHmR0AtCwXHCRTLevJ48VN9mXUjqiYEBJm1opHQ4lNgc9oz+IkTRycxUTv3waWP4x2tTnOlk/+jDPvjXF7+Au7+Fei7KRPOgQayrfhGv5w2xd900raR5Ck1lfr7mc79yCCIhnNLdNwyii5rP3v66nOFXEnth4mIx3UUoyIljrysjvV9NkoqVJLXGOSr0UEYK5bszgTif7i0IS87dbgBQIWOCxCftUbMSCxX7Z5mMxRWwafr9kOnLmcUCywlVeUwQSPuy7YmlC4Qp8mhXGmbsznTqhHupqGc9wLmN8ECd5t46R8msFEs6GqVkfIylQWNS8O+yaL+7vwLcNjq3ame0Er0WXI=
    - secure: IZB2kxIGVntQqE+wezNps/NhWB6aV9a4E9qD5WEKWjrDjHTQ24xjY+QePNWXs8NAlFs5QMbnRkdNC4CQB5N8MnXjpHLjLetN/6fRcla1JGjTurjHOxr7C+m+nL1BMBvcINZAv26dxP/eTO8TJMc96agjv3WcM4FkJd0gIWVz3KNWvdCO8XrxA8Pzx92/fbfNRJfer7lpEgfXc9z4N9osVa9t+k3RzU/S8DguQjLkEyWIxF42Whr8lwZ/1CH8oe+FgS30ppnMFs+7hFjGFINrdzAlloqIeQhratcrWTkEvilzKl07MP/V0/qFEfRTQNfVPJNzYLHcrTNdU1UtGTJMi0Yv74knSGjekvgUf87XP1dGB9vyPlJCb/zkbDcF5/Oc/Sjz0Tu5m1JKK4rgvpco/y95WjNedDhGZJ8BDMYTpA+cYOf6dSlgTpy8s2ByLeJY502z5PA3dazef6anaCNBhlra/Sm/AETjWe75/g/DCCuLm8gxtf2RWjlyYoXsVEOjaxUhXAxC0KdMqeNQ3xlELdIxq/dm933fNAPlGPmYUSgnnfozDf1dMj7HOwO1FgfkJ2SnxIA1iEL+uusIUAwP7GEbLIOgp9gtVOnLK/Yd+Ok0OTkMj7Um4LhuZQtaXtJ1QU+Yn0GcChMfFW2DdoUfCE8luirSgjhLQJmcVuAnNSo=
    - secure: H/PRQAtWszLgrAOUuCsw9nSKJ93PN9i0oPbtrWdMghsGHiEwJZcNM9zYC90mHQ+Fvg2kpHi/u/2xgnzHOqmhbdVY7LvKpNKqb2Ur3/K23HUrNkv7n2DFTYjOuJoqo/V2lM05jQrVUan4NortfKuTskvL3J1m+VuCo8kNFuR70Jm5zEz8N7egZIAcgDQslKt7AOBgEOQ1IvQO/TtgfumTQJhlMKxTfScu8y17EGeWj6SMAc2bdJWiqhXIEVrTLfOGsb1Mn6gPiZQh3nxDYn9NCTpOiPisRPOTTNHAt/MHVNtnXULjgjZv+TGHYTxo4TtVZDRLPnuKjcNfwowvYm7TWr7/gm+c2LJDptReKdj5v/8e19Kpzgn/iEtk+nc9Gi9yjVQVli+yvZ/WEg5FS4dy+lsx8IUjI98pNrZisUIubkjp4cWvPD1cVO4hw/LVJSivJYrL33BwM/VptaJ4Yt8JySx3RrfOCMlrgrhmnqs3CrQAdr4oTbuy4QxBzAUdwj3HAGuDgFKIxFvHifOvE3zWVlNpIaxLHJdHyx0eCOXLO5tDopr8lgNknWwqAjsfa4IstghI+kHXNVdF3+e/QaRIj4+rViss4AIvTYwcu8/LCImEwzHYmu1/N3lpmlglrdJSbwRCABG3V/PYSNGDK+8lE+PZtZDmzP12vCQY6iFFzRM=
    - secure: DaOIQU3G5FGigWEiOmIJ7PnUtk1C1c9tvlf1tPzlfNo8FGq42rlrpskZR04GQNQDN5zGwTqlXxRPBWNlhnlUZbIhuIBSPvT2VDOSj4bqdSQ/rLVwn+/GoyY4f06Lp0q1lr0hcdi+WbNeD22/Q9o9Zlj5p291FISN7eoy568EPLOXa/hnGvzPIF4MYR1ue1Gru+wFi+d/Vg3dMryNNIFR3PSpuwnS1TgzoEfAevM7W4pbJI8ZBbQpVQrnp80czxWKgaxlB+lKOT++VO3UCPKqifYHYn6bHz1DsIYGfcck1KPPQZJI7QLCFIdVCcjm73f6xm1bHONhZCBUONtCP+wsWZbIull7PDl5TLAxRLDv/++hvpniAE5CTLJsHwFu5Mkv67skrnU2Lfx/UYajkyt1DjgblWAyKuY9EVrg0GgoWVQF1bo3NaWQNftrI5TNf4HdAaIldpuaaEvwd4sjhF0IQ/lcbguhIF0Kz7U8NehnGPURR8WNoK5Aovi9A9QjtZjzNxBb/CqQg+SMLj9Mk8Akbd+F40ZdqeaZEwASAHPL92OORJBHfO7ldaXLOXHRV6NnnxZhd+fnSvyowXst7DX8lEmbzVZaePfwb2We0CBnwvRXpNg62KPRYOo8thidY1oVx5J24PHdTD3Q3rzTAKuM4CEdBA9YHfC30QW2mQerJck=
    - secure: f1KwWK5mLG6Fa+UbC+tljFf0nS9usX9+jmYuEUAQl3WE04AWNdC7H3eeQc9jSDL8uPGRHD21SCmEkgUlA0BaMvLvTUffToxIDilaS5H4iJvi4ck+Kh+BJ53P6Fw3WHIJodGXZ3PXDugXcj0eM2MHeFDqbKrjmCNYq6MskqbbvpPgF0c/Oy1XvIef3Y8hINfazknVeekT0v8xOcETOGom5UZQDXIhBp+vL1xCjxaF78lv8tlhOQLS/5x4NJP5fbDscKPiR/6/xPL9tKZLStl4DwXKjVkdGqtKa6NCh556QehO6UiGOW4Bh7VY6A5HImp8xvOuZ9KHoHEoJtszinIDDs251JlG2b+BMe0gEXy2LIfxVJGoXxD8ZMmnIXZRJ5ezxoE+5TrWTQCNH5vFF/u87RbVHqlTIgsrcxmXeB4mGRdUioEESQoFfvHImSwaRhJ6XbCN+Iod/fEzZ8zF/H9Tyo4e9KQ/1v/bzvYdSMVzJ0++icPlbVzaUzEEK6HYG7xAByVDNP0wq6ZfgdQoj/hwktmq1OoQrBuBgG5ciq+pfCwJItVyEOhyXUll8G9gUjEEZFzEZJZ6VIGF+s4iyGzdf4uW0C0h69EH6j5ryT0imFzacqCagOy5SCxc6D0f6fodHutdsEr7x5NWrX4Sks3yXAUecUXbceBLYWRR0nGcPVk=

addons:
  apt:
    packages: ant

before_install:
  - ant ivy-bootstrap
  - sudo apt-get -qq update
  - sudo apt-get install bash
  - sudo pip install awscli
  - eval $(aws ecr --no-include-email get-login --region us-east-1)

script:
  - "./scripts/build.sh"
  - cd solr
  - if [ -n "$TRAVIS_TAG" ]; then
      SOLR_CURR_VERSION=${TRAVIS_TAG//v/};
    fi
  - docker build --build-arg SOLR_ARG_VERSION=${SOLR_CURR_VERSION}-unbxd -t solr:latest .

after_success:
  - export PATH=$PATH:$HOME/.local/bin
  - which -a aws
  - if [ -n "$TRAVIS_TAG" ]; then $TRAVIS_BUILD_DIR/scripts/push_to_aws.sh; fi
  - "$TRAVIS_BUILD_DIR/scripts/ci.sh"

deploy:
  provider: script
  script: "cd $TRAVIS_BUILD_DIR &&  ./scripts/deploy.sh"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

notifications:
  slack:
    secure: p8c/3jqhYHnu70UafbtkLJjWxA42mxdYPsHlbzEzGTYt7VpT13AUxv0xEAG5udLc2F5xO25CMUFiE1I31vzDuMYcnHRVt2bF3OMVkGXwgWte9NseZ9ShQfHF9erif2Y4PdgwRziGAtVHoYs8ROecmsgSAs7Divm+YrTiljKg1yreof0SdUo1DUFes5Kkcs5TRnuER0HFpQWt8oYZruuLi+QC4VU3NoaUt61N6uwvcYkmare3FWWJxAUVuCuvgw2Kxl0O0WR6/y0nSgW4Zf1Tv1B9wYSx2l5h04vIdQFkSahljwT+j+sGUjrrDS4Amsteq9E3cyPNHLGDHGPePrbrCNFdsn8Lsmbx1i1/ls81pcdfXD6RTeqey4/9yZeurCNKh9tV5dxo1fupvNpGAhyrQP63i2ZYpFoPkWYgzmgQEOjD3+VLGrIb/AK1tvWgsca4tbz/Het1V0sA+TSc3398pwMxfzv4/xAKrJlLqWgAs1LnGn2qHczk98Wm6+4VjSGjycjiBmlfUHj10SqwnQH2QFCjX09iBXLu3aovnmIu5RlguWTqYEGBGquSBvpRRhG2yoeBpEF3LYB0L6qaNPdpkpfuRAmRVxGrTTEUAi+s/CkFP2zVF5ylPhzPRikWLUIIPe3wXUoWvcGLGXXEpS3nq13sw2e4NnBMOAhVuFKJxqg=
  email:
    secure: Tm8LFa8DSx4muV4B++glNeCsrKSxfwXARLLz1PH57G/OKIOQDtFPxWlbzyBbeWj0CEVQlhWSilhc7oavzKcpe0bTZr4i2z7C3uc8Vb6W/MSPYtjDV7herc2GpGaXBsjvvHqK7erbxemo5yksAb79h/bhs/DR4yhcRrtglPhssD5gPSZOeV0nC1Rwx12eUzeRsxBvdNAiGA/W6H5DxdblFSMKfWYwbhiC8LyWh20c5IK0H1ztgoIZNBdTfmLks/bkWOjVG9p2kDSvs6JaNZc9ymERnt1FFt9Is0SuhmxIkfXT1ChLaittD/u/3l9zh3YUtB4Y6ZkLlB2TFQoLZrz0DWCUzuPbjSd0gwmtqLe8pVzWyipUG5C3lv4FbSeJw3lPRzvPbWLxWhmixrV/TThJQk06VfEkxo5jquf5gosw8+Myh/zWIf9e5qsffFmkvEwF6RjhQGa0D6sD0jSBgyzXpPrVNuw0M9aRh9BhtoPCUOiPD5MsNHHwUb0DLkJB5Fg9pLqzu0t26D5w1ircgjvbv3GxWjQXRHCONOwSi8lZI2Tkv/mBljHnODmK1kqVHyZOSWDY9stAakI6M7wR9npBbjg/AIuDjJNN0VuOPrc17xupWCsyz21PMuFnBGdf1o2DKDpjbj5i14KCospnV3tus4U6lymFzmmvd+qG1azuzE8=
